services:
  app:
    image: financedock:latest
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  redis:
    image: redis:6
    ports:
      - "6379:6379"